### ISSUE TITLE
A live calendar/agenda platform feature

### ISSUE THREAD

**Issue by vanjo9800** [hackcambridge/hc2020-prototype#153]
## Place
Hackers' Dashboard

## Description
A live calendar/agenda display, so that hackers can follow it and know what is happening and when

## Current status
![image](https://user-images.githubusercontent.com/8289294/97437661-b962bf80-191b-11eb-82c8-661d61430072.png)

## Implementation steps
- [ ] Check current status (where do we get content from and how we display it)
- [ ] Embed links for incoming events
- [ ] Optional: JavaScript to gray-out past events
- [ ] Optional: Embed recording links for past events

**Comment by vanjo9800** [comment]
Update note:

So we had some initial plans we might run scripts in the HackCambridge System, but we won't during the event.

So now what we want from this is:
- check we can enter schedule and it is working okay
- embed every schedule event with a link (this should be done when adding/editing the schedule in the _Committee Dashboard_
- the graying out is optional, so make sure you finish the above tasks first
