### ISSUE TITLE
LiveStream Page

### ISSUE THREAD

**Issue by vanjo9800** [hackcambridge/hc2020-prototype#154]
## Place
Hackers' Dashboard

## Description
A livestream page where hackers can follow what is happening at real time
- Zoom/Slack/Discord link to main room (aka previous stage)
- Zoom/Slack/Discord link for different rooms
- Zoom/Slack/Discord link for previous recordings

_Suggestion:_ We can embed this in the timeline, or make it a separate submenu

## Current status
_NA_

## Implementation steps
- [ ] See embedding options for Zoom, Slack, Discord
- [ ] Test quality
- [ ] Decide a place to embed
- [ ] Build a separate menu if needed

**Comment by vanjo9800** [comment]
We decided our streams will be separate, so maybe we can only add Twitch link to the landing page, or connect each event with a link.
