### ISSUE TITLE
Sponsors and companies page

### ISSUE THREAD

**Issue by vanjo9800** [hackcambridge/hc2020-prototype#155]
## Place
Hackers' Dashboard

## Description
A page where we can list our sponsors and logos, so that hackers can learn more about them.

_Suggestion:_ We can have it as a scrollable list of logos, short summary, challenges? and maybe contact email.

## Current status
_NA_

## Implementation steps
- [ ] Decide on style
- [ ] Decide on order
- [ ] Develop a Sponsor object 
- [ ] Build a separate submenu with Sponsor objects
