### ISSUE TITLE
Challenges subpage

### ISSUE THREAD

**Issue by vanjo9800** [hackcambridge/hc2020-prototype#156]
## Place
Hackers' Dashboard

## Description
A separate page to show companies' challenges and side events we will run. To contain
- main theme
- _key_ tasks provided by companies
- any CTFs, code challenges, Among us games???

## Current status
![image](https://user-images.githubusercontent.com/8289294/97439093-a6e98580-191d-11eb-93c6-080d2ce45225.png)

## Implementation steps
- [ ] Feed current page and see what it displays
- [ ] Decide if we want a unified representation of challenges (all as tiles, or different)
- [ ] Make the main theme stand out
- [ ] Select proper challenges ordering

**Comment by vanjo9800** [comment]
Update as the issue is quite old:

We already have an existing page, so we _don't_ need a new one except if the current one is completely broken.

What we want is:
- test existing one is working with some data
- maybe update the views if we don't like it
- see if any sponsor has any requirements and add them to the existing one
