### ISSUE TITLE
Participants profile page

### ISSUE THREAD

**Issue by vanjo9800** [hackcambridge/hc2020-prototype#157]
## Place
Hackers' Dashboard

## Description
A participants profile page containing information useful for teaming up.
Possible content:
- Names and gravatar
- Slack/Discord link
- University
- small summary
- what do they want to do (make sure things are not repeating)

## Current status
_NA_

## Implementation steps
- [ ] Create a separate page for each user
- [ ] Fix URL mapping (either a GET request, or a POST that returns an HTML (weird))
- [ ] Create a participants list
- [ ] Make it searchable 😲 to easy teammatching (e.g. we search NLP and it gives you people who have NLP in their summaries, or have done NLP) -> we can see if we can do some smart searches (using an API of course!)
